#数据库连接驱动
spring:
  datasource:
    name: mydb  #数据库名
    url: jdbc:mysql://47.110.139.34:3306/feng #url
    username: root  #用户名
    password: 991029.f  #密码
    driver-class-name: com.mysql.cj.jdbc.Driver  #数据库链接驱动
#security配置
  security:
    user:
      name: fengfan
      password: 991029.f
#mvc配置
  mvc:
    view:
      prefix: /  #mvc前缀
      suffix: .html #mvc后缀
#模板配置
  thymeleaf:
    cache: false
#指定端口号
server:
  port: 80